class ParkingSpot {
  final int id;
  final String name;
  final String address;
  final double pricePerHour;
  final int availableSpots;
  final double rating;
  final double latitude;
  final double longitude;
  final String? imageUrl;
  final double? carPrice;
  final double? motoPrice;
  final bool isPrepayment;
  final bool isOvernight;
  final double distance;

  ParkingSpot({
    required this.id,
    required this.name,
    required this.address,
    required this.pricePerHour,
    required this.availableSpots,
    required this.rating,
    required this.latitude,
    required this.longitude,
    this.imageUrl,
    this.carPrice,
    this.motoPrice,
    required this.isPrepayment,
    required this.isOvernight,
    required this.distance,
  });
}

class ParkingModel {
  final String id;
  final String name;
  final String address;
  final double latitude;
  final double longitude;
  final double pricePerHour;
  final int totalSpots;
  final int availableSpots;
  final double rating;
  final String? imageUrl;
  final bool isOpen;

  ParkingModel({
    required this.id,
    required this.name,
    required this.address,
    required this.latitude,
    required this.longitude,
    required this.pricePerHour,
    required this.totalSpots,
    required this.availableSpots,
    required this.rating,
    this.imageUrl,
    required this.isOpen,
  });

  factory ParkingModel.fromJson(Map<String, dynamic> json) {
    return ParkingModel(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      address: json['address'] ?? '',
      latitude: json['latitude'] ?? 0.0,
      longitude: json['longitude'] ?? 0.0,
      pricePerHour: json['pricePerHour'] ?? 0.0,
      totalSpots: json['totalSpots'] ?? 0,
      availableSpots: json['availableSpots'] ?? 0,
      rating: json['rating'] ?? 0.0,
      imageUrl: json['imageUrl'],
      isOpen: json['isOpen'] ?? true,
    );
  }
}

// Mock data
List<ParkingSpot> mockParkingSpots = [
  // Tunis Parkings
  ParkingSpot(
    id: 1,
    name: 'Centre Ville Tunis',
    address: '123 Avenue Habib Bourguiba, Tunis',
    pricePerHour: 3.0,
    availableSpots: 15,
    rating: 4.5,
    latitude: 36.8065,
    longitude: 10.1815,
    imageUrl: null,
    carPrice: 3.0,
    motoPrice: 1.5,
    isPrepayment: true,
    isOvernight: false,
    distance: 0.8,
  ),
  ParkingSpot(
    id: 2,
    name: 'Parking Lafayette Tunis',
    address: 'Rue Charles de Gaulle, Tunis',
    pricePerHour: 2.8,
    availableSpots: 30,
    rating: 4.3,
    latitude: 36.8025,
    longitude: 10.1725,
    imageUrl: null,
    carPrice: 2.8,
    motoPrice: 1.4,
    isPrepayment: false,
    isOvernight: true,
    distance: 1.0,
  ),
  ParkingSpot(
    id: 3,
    name: 'Aéroport Tunis-Carthage',
    address: '789 Route de l\'Aéroport, Tunis-Carthage',
    pricePerHour: 5.0,
    availableSpots: 25,
    rating: 4.8,
    latitude: 36.8516,
    longitude: 10.2272,
    imageUrl: null,
    carPrice: 5.0,
    motoPrice: 2.5,
    isPrepayment: true,
    isOvernight: true,
    distance: 2.1,
  ),
  ParkingSpot(
    id: 4,
    name: 'Parking Belvédère',
    address: 'Avenue de la Liberté, Tunis',
    pricePerHour: 2.5,
    availableSpots: 40,
    rating: 4.1,
    latitude: 36.8200,
    longitude: 10.1650,
    imageUrl: null,
    carPrice: 2.5,
    motoPrice: 1.2,
    isPrepayment: false,
    isOvernight: true,
    distance: 1.5,
  ),
  ParkingSpot(
    id: 5,
    name: 'Parking Médina Tunis',
    address: 'Place de la Victoire, Médina Tunis',
    pricePerHour: 2.0,
    availableSpots: 20,
    rating: 3.9,
    latitude: 36.7979,
    longitude: 10.1706,
    imageUrl: null,
    carPrice: 2.0,
    motoPrice: 1.0,
    isPrepayment: false,
    isOvernight: false,
    distance: 1.8,
  ),
  ParkingSpot(
    id: 6,
    name: 'Parking Gammarth',
    address: 'Zone Touristique, Gammarth',
    pricePerHour: 3.5,
    availableSpots: 35,
    rating: 4.6,
    latitude: 36.9167,
    longitude: 10.2833,
    imageUrl: null,
    carPrice: 3.5,
    motoPrice: 1.8,
    isPrepayment: true,
    isOvernight: true,
    distance: 3.2,
  ),
  ParkingSpot(
    id: 7,
    name: 'Parking La Marsa',
    address: 'Avenue Habib Thameur, La Marsa',
    pricePerHour: 3.2,
    availableSpots: 28,
    rating: 4.4,
    latitude: 36.8778,
    longitude: 10.3244,
    imageUrl: null,
    carPrice: 3.2,
    motoPrice: 1.6,
    isPrepayment: false,
    isOvernight: true,
    distance: 2.5,
  ),
  
  // Sousse Parkings
  ParkingSpot(
    id: 8,
    name: 'Mall Sousse',
    address: '456 Rue de Carthage, Sousse',
    pricePerHour: 2.5,
    availableSpots: 8,
    rating: 4.2,
    latitude: 35.8256,
    longitude: 10.6369,
    imageUrl: null,
    carPrice: 2.5,
    motoPrice: 1.0,
    isPrepayment: false,
    isOvernight: true,
    distance: 1.2,
  ),
  ParkingSpot(
    id: 9,
    name: 'Parking Médina Sousse',
    address: 'Rue de la République, Sousse',
    pricePerHour: 2.0,
    availableSpots: 25,
    rating: 4.0,
    latitude: 35.8277,
    longitude: 10.6395,
    imageUrl: null,
    carPrice: 2.0,
    motoPrice: 1.0,
    isPrepayment: false,
    isOvernight: false,
    distance: 0.9,
  ),
  ParkingSpot(
    id: 10,
    name: 'Parking Port El Kantaoui',
    address: 'Port El Kantaoui, Sousse',
    pricePerHour: 3.5,
    availableSpots: 50,
    rating: 4.7,
    latitude: 35.8958,
    longitude: 10.5964,
    imageUrl: null,
    carPrice: 3.5,
    motoPrice: 1.8,
    isPrepayment: true,
    isOvernight: true,
    distance: 2.8,
  ),
  ParkingSpot(
    id: 11,
    name: 'Parking Plage Boujaafar',
    address: 'Boulevard de la Corniche, Sousse',
    pricePerHour: 2.8,
    availableSpots: 35,
    rating: 4.3,
    latitude: 35.8192,
    longitude: 10.6308,
    imageUrl: null,
    carPrice: 2.8,
    motoPrice: 1.4,
    isPrepayment: false,
    isOvernight: false,
    distance: 1.5,
  ),
  ParkingSpot(
    id: 12,
    name: 'Parking Gare Sousse',
    address: 'Avenue Mohammed V, Sousse',
    pricePerHour: 1.8,
    availableSpots: 45,
    rating: 3.8,
    latitude: 35.8295,
    longitude: 10.6402,
    imageUrl: null,
    carPrice: 1.8,
    motoPrice: 0.9,
    isPrepayment: false,
    isOvernight: true,
    distance: 1.0,
  ),
  
  // Hammamet Parkings
  ParkingSpot(
    id: 13,
    name: 'Parking Médina Hammamet',
    address: 'Avenue Habib Bourguiba, Hammamet',
    pricePerHour: 2.5,
    availableSpots: 30,
    rating: 4.4,
    latitude: 36.4000,
    longitude: 10.6167,
    imageUrl: null,
    carPrice: 2.5,
    motoPrice: 1.2,
    isPrepayment: false,
    isOvernight: false,
    distance: 0.5,
  ),
  ParkingSpot(
    id: 14,
    name: 'Parking Yasmine Hammamet',
    address: 'Zone Touristique, Yasmine Hammamet',
    pricePerHour: 4.0,
    availableSpots: 60,
    rating: 4.8,
    latitude: 36.3833,
    longitude: 10.5667,
    imageUrl: null,
    carPrice: 4.0,
    motoPrice: 2.0,
    isPrepayment: true,
    isOvernight: true,
    distance: 2.3,
  ),
  ParkingSpot(
    id: 15,
    name: 'Parking Plage Hammamet',
    address: 'Avenue de la Plage, Hammamet',
    pricePerHour: 3.0,
    availableSpots: 40,
    rating: 4.5,
    latitude: 36.4025,
    longitude: 10.6142,
    imageUrl: null,
    carPrice: 3.0,
    motoPrice: 1.5,
    isPrepayment: false,
    isOvernight: false,
    distance: 0.8,
  ),
  ParkingSpot(
    id: 16,
    name: 'Parking Nabeul-Hammamet',
    address: 'Route Touristique, Nabeul',
    pricePerHour: 2.2,
    availableSpots: 35,
    rating: 4.1,
    latitude: 36.4528,
    longitude: 10.7350,
    imageUrl: null,
    carPrice: 2.2,
    motoPrice: 1.1,
    isPrepayment: false,
    isOvernight: true,
    distance: 1.9,
  ),
  ParkingSpot(
    id: 17,
    name: 'Parking Marina Hammamet',
    address: 'Port de Plaisance, Hammamet',
    pricePerHour: 3.8,
    availableSpots: 25,
    rating: 4.6,
    latitude: 36.3992,
    longitude: 10.6158,
    imageUrl: null,
    carPrice: 3.8,
    motoPrice: 1.9,
    isPrepayment: true,
    isOvernight: true,
    distance: 1.2,
  ),
];